plugins {
    alias(libs.plugins.android.application)
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.example.musicapp'
    compileSdk 35

    defaultConfig {
        applicationId "com.example.musicapp"
        minSdk 27
        targetSdk 35
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildFeatures {
        viewBinding true
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

    //load ảnh từ link
    implementation 'com.github.bumptech.glide:glide:4.12.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.12.0'
    //tạo ảnh hình tròn
    implementation 'de.hdodenhof:circleimageview:3.1.0'
    //firebase authentication xử lý đăng nhập, đăng ký
    implementation'com.google.firebase:firebase-auth:22.1.1'
    //firebase firestore lưu email, username
    implementation 'com.google.firebase:firebase-firestore:24.9.1'
    //realtime database firebase
    implementation platform('com.google.firebase:firebase-bom:33.5.1')
    implementation("com.google.firebase:firebase-database")
    //rxJava xử lý luồng
    implementation 'io.reactivex.rxjava3:rxandroid:3.0.2'
    implementation 'io.reactivex.rxjava3:rxjava:3.1.5'
    //dùng để viết storage (lưu bài hát)
    implementation 'com.google.code.gson:gson:2.8.9'

}